bootstrap.servers=localhost:9092

group.id=connect-mqtt-cluster

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

offset.storage.topic=connect-mqtt-offsets
offset.storage.replication.factor=1

config.storage.topic=connect-mqtt-configs
config.storage.replication.factor=1

status.storage.topic=connect-mqtt-status
status.storage.replication.factor=1

offset.flush.interval.ms=10000

listeners=http://0.0.0.0:8084

plugin.path=/home/eco/kafka/plugins-mqtt
config.providers=vault
config.providers.vault.class=com.github.jcustenborder.kafka.config.vault.VaultConfigProvider

config.providers.vault.param.vault.address=${VAUT_URL}
config.providers.vault.param.vault.login.by=Token
config.providers.vault.param.vault.token=${VAUT_TOKEN}
config.providers.vault.param.vault.ssl.verify.enabled=false