apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      nodeSelector:
        role: backend
      containers:
        - name: auth
          image: 172.31.250.50:5000/eco-auth:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081

          envFrom:
            - configMapRef:
                name: auth-config

          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-vault
                  key: VAULT_TOKEN

            # same idea as docker-compose
            - name: TRUST_STORE_PATH
              value: file:/opt/vault/vault-truststore.jks

          volumeMounts:
            - name: vault-truststore
              mountPath: /opt/vault/vault-truststore.jks
              subPath: vault-truststore.jks
              readOnly: true

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 768Mi

          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20

      volumes:
        - name: vault-truststore
          secret:
            secretName: vault-truststore