bootstrap.servers=localhost:9092

group.id=connect-hdfs-cluster

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true

offset.storage.topic=connect-hdfs-offsets
offset.storage.replication.factor=1

config.storage.topic=connect-hdfs-configs
config.storage.replication.factor=1

status.storage.topic=connect-hdfs-status
status.storage.replication.factor=1

offset.flush.interval.ms=10000

rest.host.name=0.0.0.0
rest.port=8083

plugin.path=/home/eco/kafka/plugins-mqtt,/home/eco/kafka/plugins-hdfs

config.providers=vault
config.providers.vault.class=com.github.jcustenborder.kafka.config.vault.VaultConfigProvider
config.providers.vault.param.vault.address=${VAULT_ADDR}
config.providers.vault.param.vault.token=${VAULT_TOKEN}
config.providers.vault.param.vault.ssl.verify.enabled=false